In [1]:
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50,5))
scores_df = pd.DataFrame(scores,
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index=range(1,51))
scores_df.index.name = '學號'
scores_df.columns.name = '科目'

In [4]:
sum_series = scores_df.sum(axis=1)
mean_series = scores_df.mean(axis=1)
rank_series = sum_series.rank(method='min', ascending=False)
scores_df['總分'] = sum_series
scores_df['平均'] = mean_series
scores_df['排名'] = rank_series
scores_df

科目   國文   英文  數學   地理  歷史     總分       平均    排名
學號
1    80   62  50   94  52  783.6   97.950  40.0
2    77   73  75   84  54  829.6  103.700  31.0
3    73   93  82   51  67  834.2  104.275  29.0
4    58   57  71   70  73  767.8   95.975  44.0
5    57   94  86   84  53  846.8  105.850  24.0
6    62   63  63   64  75  764.4   95.550  45.0
7    58   68  56   85  64  771.2   96.400  43.0
8    97   98  83   67  91  960.2  120.025   1.0
9    89   64  69   97  97  920.2  115.025   5.0
10   82   79  87   78  95  929.2  116.150   3.0
11   59   62  82   55  63  754.2   94.275  48.0
12   55   77  97   63  85  849.4  106.175  20.0
13   66   71  98   94  65  882.8  110.350  16.0
14   64   89  66   82  74  848.0  106.000  23.0
15   67   84  80   93  90  916.8  114.600   6.0
16   85   85  50   92  90  896.4  112.050  12.0
17   58   56  52   65  51  670.4   83.800  50.0
18   61   69  74   58  60  755.4   94.425  47.0
19   68   99  75   51  66  821.8  102.725  32.0
20   97   66  86   68  55  843.4  105.425  25.0
21   74   81  61   72  83  842.2  105.275  26.0
22   66   61  50   66  73  744.2   93.025  49.0
23   78   50  85   73  93  851.8  106.475  18.0
24   61  100  51   91  99  896.4  112.050  12.0
25   96   68  95   87  72  923.6  115.450   4.0
26   71   52  89   88  66  834.2  104.275  29.0
27   76   76  69   88  89  889.6  111.200  14.0
28   83   83  88   58  57  839.8  104.975  28.0
29   52   94  82   65  65  820.6  102.575  33.0
30   60   50  88   69  82  805.8  100.725  38.0
31   62   89  75   60  50  780.2   97.525  41.0
32   69   75  73   85  75  849.4  106.175  20.0
33   70   78  70   86  51  816.0  102.000  35.0
34   59   62  79   65  58  756.6   94.575  46.0
35   86   80  84   68  92  909.0  113.625   7.0
36   71   72  76   65  69  812.6  101.575  36.0
37   61   99  83   97  57  888.4  111.050  15.0
38   87   69  89   63  98  902.2  112.775   9.0
39   87   57  64   53  75  780.2   97.525  41.0
40   65   81  62  100  75  859.6  107.450  17.0
41  100   99  99   50  74  930.4  116.300   2.0
42  100   61  82   52  82  849.4  106.175  20.0
43   55   57  71   74  88  798.0   99.750  39.0
44   99   83  69   69  83  897.6  112.200  11.0
45   64   79  99   65  63  841.0  105.125  27.0
46   66   53  75   89  96  851.8  106.475  18.0
47   79   99  61   91  77  903.4  112.925   8.0
48   66   69  89   68  66  820.6  102.575  33.0
49   90   50  69   80  63  811.4  101.425  37.0
50   80   68  92   84  80  898.8  112.350  10.0

In [5]:
scores_sorted_df = scores_df.sort_values(by='排名',ascending=True)
scores_sorted_df

科目   國文   英文  數學   地理  歷史     總分       平均    排名
學號
8    97   98  83   67  91  960.2  120.025   1.0
41  100   99  99   50  74  930.4  116.300   2.0
10   82   79  87   78  95  929.2  116.150   3.0
25   96   68  95   87  72  923.6  115.450   4.0
9    89   64  69   97  97  920.2  115.025   5.0
15   67   84  80   93  90  916.8  114.600   6.0
35   86   80  84   68  92  909.0  113.625   7.0
47   79   99  61   91  77  903.4  112.925   8.0
38   87   69  89   63  98  902.2  112.775   9.0
50   80   68  92   84  80  898.8  112.350  10.0
44   99   83  69   69  83  897.6  112.200  11.0
16   85   85  50   92  90  896.4  112.050  12.0
24   61  100  51   91  99  896.4  112.050  12.0
27   76   76  69   88  89  889.6  111.200  14.0
37   61   99  83   97  57  888.4  111.050  15.0
13   66   71  98   94  65  882.8  110.350  16.0
40   65   81  62  100  75  859.6  107.450  17.0
23   78   50  85   73  93  851.8  106.475  18.0
46   66   53  75   89  96  851.8  106.475  18.0
12   55   77  97   63  85  849.4  106.175  20.0
42  100   61  82   52  82  849.4  106.175  20.0
32   69   75  73   85  75  849.4  106.175  20.0
14   64   89  66   82  74  848.0  106.000  23.0
5    57   94  86   84  53  846.8  105.850  24.0
20   97   66  86   68  55  843.4  105.425  25.0
21   74   81  61   72  83  842.2  105.275  26.0
45   64   79  99   65  63  841.0  105.125  27.0
28   83   83  88   58  57  839.8  104.975  28.0
3    73   93  82   51  67  834.2  104.275  29.0
26   71   52  89   88  66  834.2  104.275  29.0
2    77   73  75   84  54  829.6  103.700  31.0
19   68   99  75   51  66  821.8  102.725  32.0
29   52   94  82   65  65  820.6  102.575  33.0
48   66   69  89   68  66  820.6  102.575  33.0
33   70   78  70   86  51  816.0  102.000  35.0
36   71   72  76   65  69  812.6  101.575  36.0
49   90   50  69   80  63  811.4  101.425  37.0
30   60   50  88   69  82  805.8  100.725  38.0
43   55   57  71   74  88  798.0   99.750  39.0
1    80   62  50   94  52  783.6   97.950  40.0
39   87   57  64   53  75  780.2   97.525  41.0
31   62   89  75   60  50  780.2   97.525  41.0
7    58   68  56   85  64  771.2   96.400  43.0
4    58   57  71   70  73  767.8   95.975  44.0
6    62   63  63   64  75  764.4   95.550  45.0
34   59   62  79   65  58  756.6   94.575  46.0
18   61   69  74   58  60  755.4   94.425  47.0
11   59   62  82   55  63  754.2   94.275  48.0
22   66   61  50   66  73  744.2   93.025  49.0
17   58   56  52   65  51  670.4   83.800  50.0

In [6]:
#班上前5名
scores_sorted_df.iloc[:5]

科目   國文  英文  數學  地理  歷史     總分       平均   排名
學號
8    97  98  83  67  91  960.2  120.025  1.0
41  100  99  99  50  74  930.4  116.300  2.0
10   82  79  87  78  95  929.2  116.150  3.0
25   96  68  95  87  72  923.6  115.450  4.0
9    89  64  69  97  97  920.2  115.025  5.0

In [7]:
#班上後5名
scores_sorted_df.iloc[-5:]

科目  國文  英文  數學  地理  歷史     總分      平均    排名
學號
34  59  62  79  65  58  756.6  94.575  46.0
18  61  69  74  58  60  755.4  94.425  47.0
11  59  62  82  55  63  754.2  94.275  48.0
22  66  61  50  66  73  744.2  93.025  49.0
17  58  56  52  65  51  670.4  83.800  50.0